app1/urls.py
from django.urls import path
from app1.views import *

app_name='app'

urlpatterns=[
    path('app1_hai/',app1_hai,name='app1_hai'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('app2_bye/',app2_bye,name='app2_bye'),

]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
from app1.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('app_string/',app_string,name='app_string'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def app1_hai(request):
    return render(request,'app1_hai.html')

def app_string(request):
    return HttpResponse('app_string')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_bye(request):
    return render(request,'app2_bye.html')

templates/app1_hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is App1_Hai html page</h1>

        <h2>Navigating links</h2>

        <h6><a href="{% url 'app2:app2_bye' %}">Travel to app2_bye</a></h6>
        <h6><a href="{% url 'app_string' %}">Travel app_string</a></h6>
    </center>
    
</body>
</html>

templates/app2_bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is App2_Bye html page</h1>
        <h2>Navigating links</h2>
        <h6><a href="{% url 'app:app1_hai' %}">Go to app1_hai</a></h6>
        <h6><a href="{% url 'app_string' %}">Go to app_string</a></h6>
    </center>
    
</body>
</html>